# Use an ARM64-compatible base image
FROM ubuntu:20.04

EXPOSE 9898

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update
# RUN apt-get install ffmpeg libsm6 libxext6  -y

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-aarch64.sh -b \ 
    && rm -f Miniconda3-latest-Linux-aarch64.sh \ 
    && echo "Running $(conda --version)" && \
    conda init bash && \
    . /root/.bashrc && \
    conda update conda

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /root/.EasyOCR
COPY EasyOCR/ /root/.EasyOCR/

WORKDIR /app
COPY . /app/
# RUN python -m pip install ./download/*.whl
RUN python -m pip install -r ./models/requirements.txt

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["gunicorn", "--bind", "0.0.0.0:9898", "-w", "4","app:app"]
